# my global config
global:
  scrape_interval:     300s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 300s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Add the following section to pass the --web.route-prefix option
#args:
#  - "--web.route-prefix=/prometheus"

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
    
  - job_name: 'kafka-lagexporter'
    static_configs:
     - targets: ['localhost:9991']
  - job_name: "rra-kafka-acl"
    static_configs:
     - targets: ['localhost:9991']
       labels:
         env: "rra-kafka-acl"
    relabel_configs:
     - source_labels: [__address__]
       regex: "localhost:9991"
       target_label: instance
       replacement: "kafka-broker-1"

     - source_labels: [__address__]
       regex: "localhost:9991"
       target_label: instance
       replacement: "kafka-broker-2"

     - source_labels: [__address__]
       regex: "localhost:9991"
       target_label: instance
       replacement: "kafka-broker-3"

